### ISSUE TITLE
Does it work only with Azure Queues?

### ISSUE THREAD

**Issue by sheerun** [taskcluster/generic-worker#3]
I see in code you pool from Azure Queues? Why so?

Isn't docker-worker pooling from rabbitmq?

**Comment by jonasfj** [comment]
no, docker-worker doesn't pull from rabbitmq...

The process is documented here: http://docs.taskcluster.net/queue/worker-interaction/

RabbitMQ is great for communication. But it's not ideal  for a work queue of things that shouldn't disappear. Well, it can be used as a worker queue, but it's a lot harder to make RabbitMQ highly-available, and upgrade paths aren't good in terms of message delivery guarantees.

So when storing a queue (and not just using it for communication) azure queue storage or SQS are very attractive. We went with azure because scalability limits seemed fine and it offers best-effort FIFO semantics, which is nice.

Also we can easily check the size of a RabbitMQ queue, but we can easily check the size of an azure queue.

**Comment by sheerun** [comment]
OK, thank you for an answer :)

**Comment by sheerun** [comment]
btw. It's interesting an point you make about RabbitMQ and work queues, thanks

**Comment by jonasfj** [comment]
Don't get me wrong... RabbitMQ is awesome :)

But pulse (our RabbitMQ setup) is largely configured for communication. Especially, the permission model, which is really powerful for communicating between various services.
